name: CI
on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - 'v*.*.*'
    workflow_dispatch:

permissions:
    contents: read
    id-token: write

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org

            - name: Installing Dependencies
              run: npm i

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Run Tests
              env:
                  API_USER: ${{ secrets.METACALL_API_USER }}
                  API_PASSWORD: ${{ secrets.METACALL_API_PASSWORD }}
              run: npm run test

    # faas:
    #     name: MetaCall FaaS Dispatch
    #     needs: test
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: MetaCall FaaS Workflow Dispatch
    #           uses: convictional/trigger-workflow-and-wait@v1.6.1
    #           with:
    #               owner: metacall
    #               repo: faas
    #               github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
    #               workflow_file_name: ci.yml
    #               wait_workflow: true
    #               client_payload: '{"ref": "${{ github.event.pull_request.head.sha || github.sha }}", "repo": "${{ github.event.pull_request.head.repo.full_name || github.repository }}"}'
    #               ref: master

    # deploy:
    #     name: MetaCall Deploy Dispatch
    #     needs: test
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: MetaCall Deploy Workflow Dispatch
    #           uses: convictional/trigger-workflow-and-wait@v1.6.1
    #           with:
    #               owner: metacall
    #               repo: deploy
    #               github_token: ${{ secrets.G_PERSONAL_ACCESS_TOKEN }}
    #               workflow_file_name: ci.yml
    #               wait_workflow: true
    #               client_payload: '{"ref": "${{ github.event.pull_request.head.sha || github.sha }}", "repo": "${{ github.event.pull_request.head.repo.full_name || github.repository }}"}'
    #               ref: master

    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        needs: [faas, deploy]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 24
                  registry-url: https://registry.npmjs.org

            - name: Installing Dependencies
              run: npm i

            - name: Build
              run: npm run build

            - name: Publish NPM
              run: |
                  unset NODE_AUTH_TOKEN
                  npm publish --provenance
