name: CI
on:
    pull_request:
    push:
        branches:
            - master
        tags:
            - 'v*.*.*'

jobs:
    ci:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup NodeJS
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  registry-url: https://registry.npmjs.org

            - name: Installing Dependencies
              run: npm i

            - name: Lint
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Run Tests
              run: npm run test

            - name: Publish NPM
              if: startsWith(github.ref, 'refs/tags/')
              run: npm publish --provenance
